[project]
name = "hack_for_something"
version = "0.1"
dependencies = [
  "beautifulsoup4>=4.12.3",
  "click>=8.1.7",
  "httpx>=0.27.0",
  "litestar[standard]>=2.10.0",
  "openai>=1.40.2",
  "pydantic>=2.8.2",
  "ruff>=0.5.7",
]
